/* Generated by Cython 0.29.30 */

#ifndef __PYX_HAVE__cfuncs
#define __PYX_HAVE__cfuncs

#include "Python.h"

#ifndef __PYX_HAVE_API__cfuncs

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *__pyx_f_6cfuncs_get_string(unsigned long, unsigned long, unsigned char);
__PYX_EXTERN_C PyArrayObject *__pyx_f_6cfuncs_get_strings(__Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice);
__PYX_EXTERN_C unsigned char __pyx_f_6cfuncs_get_length(double, double, double, double);
__PYX_EXTERN_C PyArrayObject *__pyx_f_6cfuncs_get_lengths(__Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice);
__PYX_EXTERN_C PyArrayObject *__pyx_f_6cfuncs_get_claim(double, double, double, double, unsigned char);
__PYX_EXTERN_C PyObject *__pyx_f_6cfuncs_get_bound(unsigned long, unsigned long, unsigned char);
__PYX_EXTERN_C PyArrayObject *__pyx_f_6cfuncs_get_bounds(__Pyx_memviewslice, __Pyx_memviewslice, __Pyx_memviewslice);

#endif /* !__PYX_HAVE_API__cfuncs */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initcfuncs(void);
#else
PyMODINIT_FUNC PyInit_cfuncs(void);
#endif

#endif /* !__PYX_HAVE__cfuncs */
